//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SC_Imperia.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Client
    {
        public int ID { get; set; }

        [Required()]
        [StringLength(50, MinimumLength = 2)]
        public string fname { get; set; }

        [Required()]
        [StringLength(50, MinimumLength = 2)]
        public string lname { get; set; }

        [Range(80000000000, 89999999999)]
        public string phone { get; set; }
        public Nullable<int> type_subID { get; set; }
        public Nullable<int> type_sports_hallID { get; set; }
        public Nullable<int> senior_staffID { get; set; }
    
        public virtual Type_sports_hall Type_sports_hall { get; set; }
        public virtual Senior_staff Senior_staff { get; set; }
        public virtual Type_sub Type_sub { get; set; }
    }
}
