//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SC_Imperia.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Senior_staff
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Senior_staff()
        {
            this.Client = new HashSet<Client>();
            this.Sports_equipment = new HashSet<Sports_equipment>();
            this.Supplier_sports_nutrition = new HashSet<Supplier_sports_nutrition>();
        }
    
        public int ID { get; set; }

        [Required()]
        [StringLength(50, MinimumLength = 2)]
        public string fname { get; set; }

        [Required()]
        [StringLength(50, MinimumLength = 2)]
        public string lname { get; set; }
        public Nullable<int> positionID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Client> Client { get; set; }
        public virtual Position Position { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sports_equipment> Sports_equipment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Supplier_sports_nutrition> Supplier_sports_nutrition { get; set; }
    }
}
