//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SC_Imperia.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Sports_equipment
    {
        public int ID { get; set; }
        public string fname { get; set; }
        public string lname { get; set; }

        [Required()]
        [Range(1, 100)]
        public Nullable<int> quantity { get; set; }

        [Required()]
        [StringLength(50, MinimumLength = 2)]
        public string title { get; set; }
        public Nullable<int> senior_staffID { get; set; }
    
        public virtual Senior_staff Senior_staff { get; set; }
    }
}
