//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SC_Imperia.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Supplier_sports_nutrition
    {
        public int ID { get; set; }

        [Required()]
        [Range(100, 1000)]
        public string quantity { get; set; }

        [Required()]
        [Range(10000, 1000000)]
        public string price { get; set; }

        [Required()]
        public string model { get; set; }
        public Nullable<int> senior_staffID { get; set; }
    
        public virtual Senior_staff Senior_staff { get; set; }
    }
}
